language: objective-c

before_install:
  - brew update
  - brew upgrade xctool
  
notifications:
  webhooks: http://progress.flatironschool.com/submissions

script: xctool -reporter json-stream -workspace PrimeTime/PrimeTime.xcworkspace -sdk iphonesimulator -destination "name=iPhone Retina (4-inch)" -scheme PrimeTime build UnitTests


